import type { FontProfile, TypePersonality } from "./types";

export const COCO_TYPE_PERSONALITY_BY_STYLE: Record<string, TypePersonality[]> = {
  afrobeats: ["afrobeats", "festival", "elegant"],
  "bottle-service": ["luxury", "minimal", "nightclub"],
  brunch: ["elegant", "editorial", "luxury"],
  edm: ["nightclub", "aggressive", "festival"],
  "general-nightlife": ["nightclub", "editorial", "aggressive"],
  "hip-hop": ["aggressive", "nightclub", "throwback"],
  house: ["minimal", "nightclub", "editorial"],
  "ladies-night": ["luxury", "elegant", "editorial"],
  "latin-night": ["latin", "elegant", "festival"],
  "luxury-club": ["luxury", "minimal", "editorial"],
  "rnb-lounge": ["elegant", "nightclub", "luxury"],
  rooftop: ["editorial", "minimal", "luxury"],
  techno: ["minimal", "aggressive", "nightclub"],
  throwback: ["throwback", "aggressive", "nightclub"],
};

export const COCO_FONT_PROFILES: FontProfile[] = [
  profile("Avigea", ["luxury", "editorial", "elegant"], 94, 48, 92, 18, 78, ["ladies-night", "luxury-club", "rooftop"], ["techno", "edm"]),
  profile("Bigtimes", ["luxury", "editorial", "elegant"], 92, 44, 88, 22, 76, ["ladies-night", "bottle-service"], ["techno"]),
  profile("Magiel Black", ["luxury", "elegant", "nightclub"], 84, 68, 78, 48, 82, ["ladies-night", "rnb-lounge", "brunch"], []),
  profile("Nexa-Heavy", ["nightclub", "aggressive", "minimal"], 62, 84, 46, 78, 90, ["hip-hop", "general-nightlife", "bottle-service"], []),
  profile("Bebas Neue", ["nightclub", "aggressive", "minimal"], 48, 88, 36, 82, 92, ["hip-hop", "edm", "throwback", "general-nightlife"], ["luxury-club", "brunch"]),
  profile("Anton", ["nightclub", "aggressive"], 45, 90, 25, 88, 90, ["hip-hop", "club", "throwback"], ["rooftop", "rnb-lounge"]),
  profile("Antonio", ["elegant", "luxury"], 72, 38, 78, 12, 56, ["ladies-night", "rnb-lounge"], ["techno", "edm", "house"]),
  profile("LEMONMILK-Bold", ["minimal", "luxury", "nightclub"], 72, 74, 70, 48, 88, ["bottle-service", "luxury-club", "general-nightlife"], []),
  profile("LEMONMILK-Regular", ["minimal", "editorial", "elegant"], 70, 58, 72, 30, 90, ["luxury-club", "rnb-lounge", "rooftop"], []),
  profile("LEMONMILK-Light", ["luxury", "minimal", "editorial"], 86, 38, 88, 12, 82, ["bottle-service", "luxury-club", "rnb-lounge"], ["hip-hop", "edm"]),
  profile("Nexa-ExtraLight", ["luxury", "minimal", "editorial"], 88, 34, 90, 10, 80, ["luxury-club", "rooftop"], ["hip-hop"]),
  profile("Coolvetica Rg Cond", ["throwback", "nightclub", "editorial"], 50, 76, 48, 58, 86, ["throwback", "house", "general-nightlife"], []),
  profile("Coolvetica Hv Comp", ["throwback", "aggressive", "nightclub"], 44, 84, 36, 74, 84, ["throwback", "hip-hop"], []),
  profile("Octin College Rg", ["throwback", "aggressive"], 36, 82, 28, 78, 82, ["throwback", "sports", "hip-hop"], ["luxury-club"]),
  profile("Monoton", ["throwback", "festival", "nightclub"], 38, 82, 42, 55, 68, ["throwback", "disco"], ["luxury-club", "rooftop"]),
  profile("Lovelo Black", ["throwback", "nightclub", "editorial"], 58, 84, 64, 62, 86, ["throwback", "general-nightlife", "house", "rooftop"], []),
  profile("Metropolis 1920", ["throwback", "luxury", "editorial"], 82, 62, 86, 30, 76, ["throwback", "luxury-club", "bottle-service", "rooftop"], ["techno", "edm"]),
  profile("Azonix", ["minimal", "nightclub", "aggressive"], 56, 86, 48, 72, 82, ["techno", "edm", "house"], ["ladies-night"]),
  profile("Dune_Rise", ["minimal", "nightclub", "aggressive"], 58, 84, 52, 68, 80, ["techno", "edm"], ["brunch"]),
  profile("Moderniz", ["minimal", "nightclub"], 60, 78, 55, 54, 82, ["techno", "house"], []),
  profile("Techno Hideo", ["aggressive", "nightclub"], 36, 92, 24, 88, 72, ["techno", "edm"], ["luxury-club"]),
  profile("Aliens Among Us", ["aggressive", "nightclub", "festival"], 34, 90, 22, 84, 64, ["edm", "techno"], ["luxury-club", "rooftop"]),
  profile("TR2N", ["nightclub", "minimal"], 42, 84, 38, 66, 76, ["edm", "techno"], []),
  profile("Tropical Avenue", ["afrobeats", "latin", "festival"], 58, 82, 62, 48, 78, ["afrobeats", "latin-night", "brunch"], ["techno"]),
  profile("African", ["afrobeats", "festival"], 46, 82, 50, 54, 70, ["afrobeats"], ["luxury-club"]),
  profile("ChettaVissto", ["afrobeats", "festival", "latin"], 48, 80, 48, 60, 72, ["afrobeats", "latin-night"], []),
  profile("DIMITRI_", ["aggressive", "nightclub", "latin"], 44, 86, 36, 78, 76, ["latin-night", "hip-hop"], []),
  profile("Designer", ["luxury", "editorial", "nightclub"], 78, 68, 74, 44, 78, ["luxury-club", "bottle-service"], []),
  profile("Game Of Squids", ["aggressive", "nightclub"], 36, 88, 24, 82, 68, ["edm", "techno", "hip-hop"], ["luxury-club"]),
  profile("PaybAck", ["aggressive", "throwback"], 30, 88, 22, 88, 66, ["hip-hop", "throwback"], ["rooftop"]),
  profile("Galaxia Personal Used", ["nightclub", "festival"], 36, 84, 30, 72, 66, ["edm", "techno"], []),
  profile("OpenScript", ["elegant", "luxury", "festival"], 76, 54, 86, 16, 76, ["ladies-night", "brunch", "rnb-lounge"], ["techno"]),
  profile("Dear Script (Demo_Font)", ["luxury", "elegant"], 84, 44, 90, 12, 70, ["luxury-club", "ladies-night"], ["edm"]),
  profile("Adelia Alternate", ["luxury", "elegant"], 82, 48, 88, 14, 72, ["ladies-night", "rnb-lounge"], []),
  profile("Good Brush", ["festival", "afrobeats", "throwback"], 38, 82, 46, 62, 72, ["afrobeats", "throwback", "brunch"], ["luxury-club"]),
  profile("Aqilah-JRYXK", ["elegant", "latin", "festival"], 72, 62, 80, 24, 74, ["latin-night", "ladies-night", "afrobeats"], []),
  profile("Road Rage", ["aggressive", "throwback"], 24, 92, 18, 90, 62, ["throwback", "hip-hop"], ["luxury-club"]),
];

function profile(
  family: string,
  personalities: TypePersonality[],
  luxury: number,
  energy: number,
  elegance: number,
  aggression: number,
  readability: number,
  bestFor: string[],
  avoidFor: string[]
): FontProfile {
  return {
    aggression,
    avoidFor,
    bestFor,
    elegance,
    energy,
    family,
    luxury,
    personalities,
    readability,
  };
}
