/** Reviewed questions for authored slots whose IDs/editor roles are misleading.
 * These describe existing text owners only; they never add objects to a flyer.
 */
export type CocoFormObjectContract = { role?: string; labelFor?: string; label?: string; guidance?: string; group?: string; maxLines?: number };
const automatic: CocoFormObjectContract = { role: 'designCopy' };
const tables: CocoFormObjectContract = { label: 'Table availability', guidance: 'Add table info, like VIP Tables Available.', group: 'Experience & specials' };
const highlights: CocoFormObjectContract = { label: 'Event highlights', guidance: 'List what’s available, like hookah, food, drinks, or VIP tables.' };
export const COCO_FORM_OBJECT_CONTRACTS: Record<string, Record<string, CocoFormObjectContract>> = {
  'brunch-sundays': {
    b1:{role:'boundLabel',labelFor:'dj2'}, b2:{role:'boundLabel',labelFor:'dj3'},

    mood:automatic,motto:automatic,tagline:automatic,mug:automatic,
    offer:{role:'offers',label:'Brunch offer',guidance:'Add your price or package, like Brunch $35 per person.'},
    included:{role:'eventDetails',label:'Food included',guidance:'Say what the brunch price includes.'},
    drinks:{role:'drinkSpecials',label:'Drinks included',guidance:'Add the drinks package and duration.'},
    venuecaption:{role:'venueCaption',label:'Venue description'},
    contact:{role:'contacts',label:'Reservations',guidance:'Add a booking number or contact.'},
    age:{role:'ageRequirement'},
  },
  'girl-code': { mood: automatic, motto: automatic, tagline: automatic, venuecaption: {role:'venueCaption',label:'Venue description',guidance:'Add a short description below the venue name.'}, contactlabel: {role:'boundLabel',labelFor:'contact'}, contact:{role:'contacts',label:'Table reservations',guidance:'Add the phone number or booking contact for tables.'}, endtime:{role:'endTime'}, djlabel:{role:'boundLabel',labelFor:'dj1'}, genres:{role:'musicPolicy'} },
  'ycee-live': {motto:automatic,presents:{role:'boundLabel',labelFor:'presenter'},doors:{role:'boundLabel',labelFor:'time'},contactlabel:{role:'boundLabel',labelFor:'contact'},contact:{role:'contacts',label:'Reservations contact'},brandname:{label:'Venue logo name',guidance:'Optional short name below the venue monogram.'},brandcity:{label:'Venue logo location',guidance:'Optional city beneath the venue logo name.'},brandmark:{role:'boundLabel',labelFor:'brandName'},rdate:{role:'boundLabel',labelFor:'date'},rvenue:{role:'boundLabel',labelFor:'venue'},rcontact:{role:'boundLabel',labelFor:'contact'},age:{role:'ageRequirement'}},
  'honey-nights': { mood:automatic,motto:automatic,tagline:automatic,presents:{role:'boundLabel',labelFor:'presenter'},djlabel:{role:'boundLabel',labelFor:'dj1'},rdjs:{role:'boundLabel',labelFor:'dj1'},genres:{role:'musicPolicy'},age:{role:'ageRequirement'},rage:{role:'boundLabel',labelFor:'age'},rtime:{role:'boundLabel',labelFor:'time'} },
  'girl-code-rose': { contactplate:{role:'boundLabel',labelFor:'contact'}, mood: automatic, motto: automatic, tagline: automatic, venuecaption: {role:'venueCaption',label:'Venue description',guidance:'Add a short description below the venue name.'}, contactlabel: {role:'boundLabel',labelFor:'contact'}, contact:{role:'contacts',label:'Table reservations',guidance:'Add the phone number or booking contact for tables.'}, endtime:{role:'endTime'}, djlabel:{role:'boundLabel',labelFor:'dj1'}, genres:{role:'musicPolicy'} },
  'soft-life': {
    tagline: automatic, motto: automatic, badgetitle: automatic, badgecaption: automatic, signoff: automatic,
    djlabel: { role: 'boundLabel', labelFor: 'dj1' },
    dresslabel: { role: 'boundLabel', labelFor: 'dress' },
    genres: { role: 'musicPolicy' },
    experience: { role: 'eventDetails', label: 'Event experience', guidance: 'Add the atmosphere and activities, one short line per row.' },
    entry: { role: 'freeEntryCondition' },
    dress: { role: 'dressCode' },
  },
  'grills-and-groove': { ampersand: automatic, tagline: automatic, djlabel: {role:'boundLabel',labelFor:'dj1'}, genres:{role:'musicPolicy'}, specials:{role:'drinkSpecials',label:'Dinner & drink specials',guidance:'Add dinner hours and cocktail offers, one per line.'}, reservations:{role:'eventDetails',label:'Reservations & age',guidance:'Add reservation advice and the age limit.'} },
  'space-neon': {
    subtag: automatic,
    guest: { role: 'performers', label: 'Guest name', guidance: 'Add the guest or artist name. The Special Guest heading is already on your flyer.' }, guestlabel: automatic,
    offer: { role: 'entryFee', label: 'Entry / ticket price', guidance: 'Tell guests what it costs to get in. Line 1: Entry or Tickets. Line 2: the price, like $20, or Free.', group: 'Admission' },
    contact: { role: 'socialWebsite', label: 'Social handle & website', guidance: 'Add your @handle and website on one line, like @nightcrew, nightcrew.com.', group: 'Reservations, socials & QR' },
  },
  'day-party': { details: { role: 'musicPolicy' }, escape: automatic },
  'ladies-night-rose': { musiclabel: { role: 'boundLabel', labelFor: 'lineup' }, lineup: { role: 'musicPolicy' }, experience: automatic },
  'branch-happy-hour': { genres: { role: 'drinkSpecials', label: 'Drinks on offer', guidance: 'List the drinks, one short line per box.' }, presenter: automatic },
  'afrobeat-rooftop': { invitation: tables },
  'sunset-yacht': { invitation: tables },
  'aura': { genres: automatic, description: highlights },
  'bass-pressure': { description: automatic },
  'en-blanc': { description: automatic },
  'euphoria': { presenter: automatic, tickets: automatic },
  'in-crowd': { genres: automatic, description: automatic, vip: tables, reservation: { label: 'Reservation instructions', guidance: 'Tell people how to book a table or join the guest list.' } },
  'karaoke-night': { genres: { role: 'eventDetails', ...highlights } },
  'ladies-secret': { detailslabel: { role: 'boundLabel', labelFor: 'genres' }, genres: { role: 'hosts', label: 'Hosts / hype team' }, description: automatic, vip: tables },
  'mardi-gras': { genres: automatic, description: automatic },
  'martini-night': { genres: automatic },
  'mind-state': { genres: automatic, description: highlights },
  'mojito-monday': { genres: automatic, description: automatic },
  'nocturne-muse': { description: automatic, vip: tables, genres: { label: 'Music and atmosphere', guidance: 'Add the music and vibe, one short line per box.' } },
  'one-love-reggae': { footer: automatic },
  'salsa-noche': { footer: automatic, tagline: automatic },
  'sip-and-paint': { genres: automatic, footer: { label: 'Age & guest reminders', guidance: 'Add the age limit and guest reminders, separated by |, like 21+ | Drink Responsibly.' } },
  'slow-jamz': { description: automatic },
  'soiree-dream-house': { genres: automatic, footer: automatic, offer: { role: 'freeEntryCondition' } },
  'sugar-rush': { description: automatic },
  'taco-tuesday': { presenter: automatic, genres: automatic, description: { role: 'promotionDeadline', label: 'Special hours', guidance: 'Say when the specials run, like All Night or Until 11PM.' } },
  'throwback-saturdays': { compliance: { label: 'Time, age & dress code', guidance: 'Add the hours, age limit, and dress code, separated by |, like 10PM–Late | 21+ | All White.' } },
  'yacht-escape': { footer: { role: 'ticketLink', label: 'Ticket website', guidance: 'Add the website where guests can get tickets.' }, aside: automatic },
  'fashion-club-vertical': { footer: automatic, genres: automatic },
  'neon-night-shift': { genres: automatic, doors: automatic, offers: highlights },
  'glow-in-the-dark': { rail: automatic },
  'punta-cana-sundays': { genres: automatic, tropical: automatic, dress: automatic },
  'city-nights': { callout: automatic, slogan: automatic },
  'black-gold-party': { details: { label: 'Parking & free entry', guidance: 'Add the parking info and who gets in free, separated by |.' } },
  'brunch-saturday': { band: { role: 'performers', label: 'Live entertainment', guidance: 'Add the live band or act, like Live Acoustic Band.' } },
  pulse: { details: { label: 'What the discount covers', guidance: 'Say what the discount applies to, like All Menu Items or Cocktails.' } },
  'zona-de-perreo': { details: { label: 'Entry & bottle service', guidance: 'Line 1: who gets free entry and until when. Line 2: your bottle-service info.' } },
  'diabla-all-white': { footer: automatic },
  'rnb-thursdays': { attractions: highlights },
  'reggae-jams': { attractions: highlights },
  'elite-monday': {
    corporate: automatic,
    artist: { role: 'venueName', label: 'Venue name', guidance: 'Add the venue name, like The Loft.', maxLines: 1 },
    onwards: { role: 'boundLabel', labelFor: 'time' },
    special: { role: 'djs', label: 'DJ name', guidance: 'Add the DJ name, like Nova. The DJ label is already included.' },
    dj: { role: 'boundLabel', labelFor: 'special' },
    featuring: { role: 'boundLabel', labelFor: 'special' },
    djframe: { labelFor: 'special' },
    rule: { labelFor: 'special' },
  },
  'we-outside': {
    brand: { role: 'brandInitials', label: 'Brand initials', guidance: 'Add the short initials at the top left, like DC.', group: 'Event details', maxLines: 1 },
    presenter: { role: 'presenterName', label: 'Brand / venue name', guidance: 'Add the name below the initials, like Deon’s Cave.' },
    legal: { role: 'ageRequirement' },
  },
  'brunch-vibes': { details: automatic, footer: automatic },
  'grey-rave-festival': { footermessage: automatic },
  'dodge-night-rides': { slogan: automatic, features: highlights },
};
export function cocoFormObjectContract(recipe: string, objectId: string): CocoFormObjectContract | undefined {
  return COCO_FORM_OBJECT_CONTRACTS[recipe]?.[objectId.replace(/[-_]/g, '').toLowerCase()];
}
