export { chooseCocoLayoutTournamentWinner, passesFatalGates } from "./engine";
export type {
  CocoCompositionBlock,
  CocoCompositionPatternId,
  CocoCompositionRole,
  CocoCompositionSource,
  CocoCompositionSystem,
  CocoCopyTreatment,
  CocoCreativeBrief,
  CocoCreativeStoryId,
  CocoEyeFlowStep,
  CocoInformationGroup,
  CocoLayoutCandidate,
  CocoRendererZoneMap,
  CocoTournamentAlign,
  CocoTournamentFormat,
  CocoTournamentLayoutId,
  CocoTournamentRect,
  CocoTournamentResult,
  CocoTournamentScore,
  CocoTournamentSnapshot,
  CocoTournamentText,
  CocoTournamentZoneMap,
} from "./types";
