import type { ArtDirectorInput } from "./types.ts";

export const MOJITO_ART_DIRECTOR_FIXTURE: ArtDirectorInput = {
  scene: {
    confidence: 0.93,
    creativeDecisions: {
      story: "luxury-tropical-brunch",
      marketingIntent: "sell-lifestyle",
      hero: { type: "subject", id: "subject-1", confidence: 0.98 },
      composition: {
        typeField: "left",
        preferredPattern: "left-premium-stack",
        stackAlignment: "left",
        stackRect: { x: 6, y: 13, width: 46, height: 72 },
        overlapPolicy: "subtle",
      },
      densityPolicy: {
        policy: "low",
        maxVisibleGroups: 6,
        maxBodyLines: 3,
      },
      effectPolicy: { policy: "restrained" },
      colorStory: { id: "tropical-emerald" },
    },
    protectionZones: [
      {
        target: "face",
        rect: { x: 59, y: 14, width: 29, height: 32 },
        importance: "critical",
        allowOverlapRatio: 0,
      },
      {
        target: "drink",
        rect: { x: 59, y: 62, width: 15, height: 25 },
        importance: "high",
        allowOverlapRatio: 0.05,
      },
    ],
  },
  creativeDirection: {
    id: "direction-mojito",
    posterIdentity: "lifestyle-editorial",
    posterDNA: "tropical-lifestyle",
    marketingGoal: "sell-lifestyle",
    emotionalGoal: "relaxed-luxury",
    visualEnergy: "medium",
    creativeRisk: "controlled",
    informationDensity: "low",
    composition: {
      family: "left-premium-stack",
      typeField: "left",
      alignment: "left",
      stackRect: { x: 6, y: 13, width: 46, height: 72 },
      overlapPolicy: "subtle",
      oneColumn: true,
    },
    hierarchy: {
      headlinePower: 100,
      accentMaxRatio: 0.42,
      bodyMaxRatio: 0.25,
      dateMaxRatio: 0.24,
      venueMaxRatio: 0.18,
      badgeMaxRatio: 0.2,
      presenterMaxRatio: 0.13,
      headlineMustWinBy: 1.9,
    },
    signatureMove: {
      move: "script-cross",
      target: "accent",
      intensity: "medium",
    },
  },
  composition: {
    id: "composition-mojito",
    family: "left-premium-stack",
    alignment: "left",
    typeField: "left",
    stackRect: { x: 6, y: 13, width: 46, height: 72 },
    subjectRect: { x: 47, y: 2, width: 53, height: 98 },
    faceRect: { x: 59, y: 14, width: 29, height: 32 },
    badgeRect: { x: 85, y: 7, width: 10, height: 10 },
    score: {
      balance: 91,
      originality: 82,
    },
  },
  copyArchitecture: {
    id: "copy-mojito",
    groups: [
      { id: "identity", role: "identity", treatment: "hero", text: "MOJITO\nMONDAZE", maxLines: 2, powerRatio: 1 },
      { id: "emotion", role: "emotion", treatment: "accent", text: "Brunch Vibes", maxLines: 1, powerRatio: 0.42 },
      { id: "experience", role: "experience", treatment: "metadata", text: "TROPICAL RHYTHMS • AFROBEATS • LATIN\nCOCKTAILS & ISLAND ENERGY", maxLines: 2, powerRatio: 0.25 },
      { id: "logistics", role: "logistics", treatment: "metadata", text: "MONDAY • 4PM TIL LATE", maxLines: 1, powerRatio: 0.24 },
      { id: "venue", role: "venue", treatment: "footer", text: "SKY LOUNGE MIAMI", maxLines: 1, powerRatio: 0.18 },
      { id: "badge", role: "badge", treatment: "badge", text: "ENTRY\n$50", maxLines: 2, powerRatio: 0.2 },
    ],
  },
  typography: {
    id: "type-mojito",
    maxFontFamilies: 2,
    fontFamilies: ["Bebas Neue", "Great Vibes"],
    headline: { role: "headline", text: "MOJITO\nMONDAZE", fontFamily: "Bebas Neue", visualPower: 100, maxLines: 2 },
    accent: { role: "accent", text: "Brunch Vibes", fontFamily: "Great Vibes", visualPower: 40, maxLines: 1 },
    metadata: { role: "metadata", fontFamily: "Bebas Neue", visualPower: 24, maxLines: 2 },
    dateTime: { role: "dateTime", fontFamily: "Bebas Neue", visualPower: 22, maxLines: 1 },
    venue: { role: "venue", fontFamily: "Bebas Neue", visualPower: 16, maxLines: 1 },
    badge: { role: "badge", fontFamily: "Bebas Neue", visualPower: 18, maxLines: 2 },
  },
  color: {
    id: "color-mojito",
    policy: "tropical-emerald",
    strongColors: ["#173E30", "#F4EBDD", "#B9C94A"],
    roles: [
      { role: "headline", color: "#F4EBDD", contrastRatio: 6.8, importance: "critical" },
      { role: "accent", color: "#B9C94A", contrastRatio: 4.2, importance: "high" },
      { role: "metadata", color: "#D8D1C4", contrastRatio: 4.6, importance: "high" },
    ],
  },
  effects: {
    id: "effects-mojito",
    policy: "restrained",
    oneSignatureEffect: true,
  },
  renderedSnapshot: {
    width: 1080,
    height: 1080,
    format: "square",
    subjectRect: { x: 47, y: 2, width: 53, height: 98 },
    faceRect: { x: 59, y: 14, width: 29, height: 32 },
    gazeRect: { x: 35, y: 5, width: 24, height: 20 },
    elements: [
      {
        id: "headline",
        role: "headline",
        rect: { x: 7, y: 17, width: 42, height: 24 },
        text: "MOJITO\nMONDAZE",
        visible: true,
        opacity: 1,
        fontFamily: "Bebas Neue",
        fontSize: 120,
        fontWeight: 700,
        tracking: -0.03,
        lineHeight: 0.82,
        lineCount: 2,
        align: "left",
        color: "#F4EBDD",
        contrastRatio: 6.8,
        visualPower: 100,
        effects: { glow: 0.06, shadow: 0.22, stroke: 0.02, blur: 0 },
      },
      {
        id: "accent",
        role: "accent",
        rect: { x: 10, y: 39, width: 34, height: 9 },
        text: "Brunch Vibes",
        visible: true,
        opacity: 1,
        fontFamily: "Great Vibes",
        fontSize: 50,
        fontWeight: 500,
        lineCount: 1,
        align: "left",
        rotationDeg: -5,
        color: "#B9C94A",
        contrastRatio: 4.2,
        visualPower: 40,
        effects: { glow: 0.03, shadow: 0.12, stroke: 0, blur: 0 },
      },
      {
        id: "metadata",
        role: "metadata",
        rect: { x: 8, y: 50, width: 38, height: 10 },
        text: "TROPICAL RHYTHMS • AFROBEATS • LATIN\nCOCKTAILS & ISLAND ENERGY",
        visible: true,
        opacity: 1,
        fontFamily: "Bebas Neue",
        fontSize: 26,
        fontWeight: 600,
        lineCount: 2,
        align: "left",
        color: "#D8D1C4",
        contrastRatio: 4.6,
        visualPower: 24,
        effects: { glow: 0, shadow: 0.1, stroke: 0, blur: 0 },
      },
      {
        id: "dateTime",
        role: "dateTime",
        rect: { x: 8, y: 63, width: 32, height: 5 },
        text: "MONDAY • 4PM TIL LATE",
        visible: true,
        opacity: 1,
        fontFamily: "Bebas Neue",
        fontSize: 24,
        fontWeight: 600,
        lineCount: 1,
        align: "left",
        color: "#D8D1C4",
        contrastRatio: 4.5,
        visualPower: 22,
        effects: { glow: 0, shadow: 0.08, stroke: 0, blur: 0 },
      },
      {
        id: "venue",
        role: "venue",
        rect: { x: 8, y: 70, width: 30, height: 4 },
        text: "SKY LOUNGE MIAMI",
        visible: true,
        opacity: 0.9,
        fontFamily: "Bebas Neue",
        fontSize: 19,
        fontWeight: 500,
        lineCount: 1,
        align: "left",
        color: "#D8D1C4",
        contrastRatio: 4.1,
        visualPower: 16,
        effects: { glow: 0, shadow: 0.05, stroke: 0, blur: 0 },
      },
      {
        id: "badge",
        role: "badge",
        rect: { x: 85, y: 7, width: 10, height: 10 },
        text: "ENTRY\n$50",
        visible: true,
        opacity: 1,
        fontFamily: "Bebas Neue",
        fontSize: 18,
        fontWeight: 700,
        lineCount: 2,
        align: "center",
        color: "#111111",
        backgroundColor: "#B9C94A",
        contrastRatio: 8.2,
        visualPower: 18,
        effects: { glow: 0, shadow: 0.12, stroke: 0, blur: 0 },
      },
    ],
    globalMetrics: {
      visibleGroupCount: 6,
      uniqueFontCount: 2,
      strongColorCount: 3,
      previewExportMatch: true,
      exportClipped: false,
      safeMarginViolations: 0,
    },
  },
  userPreferences: {
    strictness: "balanced",
    minimumExportScore: 75,
    preserveUserMoves: false,
    allowAutomaticFixes: true,
    maxIterations: 4,
    minExpectedGain: 3,
  },
};
