// nightlife-flyers/localFontMap.ts

// Loadable for saved template artwork, excluded from general font menus.
export const TEMPLATE_ONLY_FONT_FAMILIES = new Set(['Bad Girls Brush PNG', 'Bad Girls Pink PNG', 'Glow Chrome PNG', 'Eaden Gold PNG', 'Bass Pressure Blue PNG', 'Ladies Neon Chrome PNG', 'Reggae Jams Script PNG', 'Ladies Night Pink PNG', 'Ladies Rose Gold PNG']);

export const FONT_FILE_MAP: Record<string, string> = {
  "Spotlight Gold PNG": "/fonts/SpotlightGoldPNG.woff2?v=1",
  "Honey Gold Serif PNG": "/fonts/HoneyGoldSerifPNG.woff2?v=1",
  "Rose Chrome Serif PNG": "/fonts/RoseChromeSerifPNG.woff2?v=1",
  // Canonical PNG names; legacy entries below preserve saved projects.
  "Future Outline PNG": "/fonts/Future02PNG.woff2",
  "Liquid Chrome PNG": "/fonts/ChromePNG.woff2",
  "Circuit Lines PNG": "/fonts/FuturePNG.woff2",
  "Distressed Ink PNG": "/fonts/GrungePNG.woff2",
  "Tribal Pattern PNG": "/fonts/AfroPNG.woff2",
  "Rainbow Gradient PNG": "/fonts/RainbowPNG.woff2",
  "Whimsical Gold PNG": "/fonts/GoldWhimsicalPNG.woff2",
  "Rose Fur PNG": "/fonts/PinkFurPNG.woff2",
  "Calligraphy Gold PNG": "/fonts/GoldScriptPNG.woff2",
  "Classic Gold Serif PNG": "/fonts/GoldSerifPNG.woff2?v=3",
  "Block Gold PNG": "/fonts/GoldPNG.woff2?v=2",
  "Clean Gold PNG": "/fonts/CleanGoldPNG.woff2?v=1",
  "Crimson Neon PNG": "/fonts/RedNeonPNG.woff2",
  "Arctic Metal PNG": "/fonts/ArcticMetalPNG.woff2",
  "Gold Flourish PNG": "/fonts/GoldFlourishPNG.woff2",
  "Gold Filigree PNG": "/fonts/GoldFiligreePNG.woff2",
  "Africa Gold PNG": "/fonts/AfricaGoldPNG.woff2?v=2",
  "Sunset Gold PNG": "/fonts/SunsetGoldPNG.woff2",
  "Future 02 PNG": "/fonts/Future02PNG.woff2",
  "Chrome PNG": "/fonts/ChromePNG.woff2",
  "Future PNG": "/fonts/FuturePNG.woff2",
  "Grunge PNG": "/fonts/GrungePNG.woff2",
  "Afro PNG": "/fonts/AfroPNG.woff2",
  "Rainbow PNG": "/fonts/RainbowPNG.woff2",
  "Gold Whimsical PNG": "/fonts/GoldWhimsicalPNG.woff2",
  "Pink Fur PNG": "/fonts/PinkFurPNG.woff2",
  "Gold Script PNG": "/fonts/GoldScriptPNG.woff2",
  "Gold Serif PNG": "/fonts/GoldSerifPNG.woff2?v=3",
  "Red Neon PNG": "/fonts/RedNeonPNG.woff2",
  "Gold PNG": "/fonts/GoldPNG.woff2?v=2",
  "Ladies Neon Chrome PNG": "/fonts/LadiesNeonChromePNG.woff2",
  "Paint Splash Serif PNG": "/fonts/PaintSplashSerifPNG.woff2",
  "Sunset Paint Brush PNG": "/fonts/SunsetPaintBrushPNG.woff2?v=2",
  "Euphoria Chrome PNG": "/fonts/EuphoriaChromePNG.woff2",
  "Mojito Serif PNG": "/fonts/MojitoSerifPNG.woff2?v=4",
  "Textured Gold Serif PNG": "/fonts/TexturedGoldSerifPNG.woff2",
  "Glow Chrome PNG": "/fonts/GlowChromePNG.woff2?v=2",
  "Neon Green PNG": "/fonts/NeonGreenPNG.woff2",
  "Eaden Gold PNG": "/fonts/EadenGoldPNG.woff2?v=2",
  "Reggae Jams Script PNG": "/fonts/ReggaeJamsScriptPNG.woff2?v=2",
  "Bad Girls Brush PNG": "/fonts/BadGirlsBrushPNG.woff2?v=3",
  "Bad Girls Pink PNG": "/fonts/BadGirlsPinkPNG.woff2?v=3",
  "Ladies Rose Gold PNG": "/fonts/LadiesRoseGoldPNG.woff2?v=3",
  "Ladies Night Pink PNG": "/fonts/LadiesNightPinkPNG.woff2?v=1",
  "Bass Pressure Blue PNG": "/fonts/BassPressureBluePNG.woff2",
  "Bold Paint SVG": "/fonts/BoldPaintSVG.woff2",
  "Drift Brush SVG": "/fonts/DriftBrushSVG.woff2",
  "Offshore SVG": "/fonts/OffshoreSVG.woff2",
  "Whimsical SVG": "/fonts/WhimsicalSVG.woff2?v=2",
  "Billion Dreams": "/fonts/billion_dreams/BillionDreams_PERSONAL.ttf",
  "Muthiara": "/fonts/muthiara/Muthiara demo version.otf",
  "Dopestyle": "/fonts/dopestyle/Dopestyle.ttf",
  "Creamer": "/fonts/creamer/Creamer.otf",
  "Transcity": "/fonts/transcity/Transcity DEMO.otf",
  // --- STABLE PATHS (No spaces/special chars) ---
  "DIMITRI_": "/fonts/DIMITRI_.TTF",
  "Aliens Among Us": "/fonts/Aliens-Among-Us.ttf",
  "Game Of Squids": "/fonts/Game-Of-Squids.ttf",
  "Aqilah-JRYXK": "/fonts/Aqilah-JRYXK.ttf",
  "EdgeOfTheGalaxyRegular-OVEa6": "/fonts/EdgeOfTheGalaxyRegular-OVEa6.ttf",
  "raidercrusader": "/fonts/raidercrusader.ttf",
  "Oups": "/fonts/Oups.ttf",
  "Doctor Glitch": "/fonts/Doctor-Glitch.ttf",
  "Brittany Signature": "/fonts/brittany_signature/BrittanySignature.ttf",
  "Northwell": "/fonts/Northwell-GraphicEx.com/Northwell/Northwell.otf",
  "Northwell Alt": "/fonts/Northwell-GraphicEx.com/Northwell/Northwell-Alt.otf",
  "Northwell Swash": "/fonts/Northwell-GraphicEx.com/Northwell/Northwell-Swash.otf",
  "Another Danger": "/fonts/another_danger/Another Danger - Demo.otf",
  "Another Danger Slanted": "/fonts/another_danger/Another Danger Slanted - Demo.otf",
  "Dear Script (Demo_Font)": "/fonts/dear-script-demo-font.ttf",
  "edosz": "/fonts/edosz.ttf",
  "Galaxia Personal Used": "/fonts/Galaxia-Personal-Used.ttf",
  "Dune_Rise": "/fonts/dune-rise.ttf",
  "who asks satan": "/fonts/who-asks-satan.ttf",
  "African": "/fonts/African.ttf",
  "Asectica Simple Demo": "/fonts/Asectica Simple Demo.ttf",
  "Paint the town": "/fonts/Paint the town-1.ttf",
  "jelani": "/fonts/jelani.otf",
  "Broken Glass": "/fonts/BrokenGlass.ttf",
  "Monoton": "/fonts/Monoton-Regular.ttf",
  "Magiel Black": "/fonts/Magiel-Black.otf",
  "Good Brush": "/fonts/script/Good Brush.otf",
  "Georgia Brush": "/fonts/georgia_brush/Georgia Brush.otf",
  "Hong Kong Script Brush": "/fonts/hong_kong_script_brush/Hong Kong Script Brush.ttf",
  "Road Rage": "/fonts/script/Road_Rage.otf",
  "Mitshuka": "/fonts/script/Mitshuka.otf",
  "Bigtimes": "/fonts/script/Bigtimes.otf",
  "Adelia Alternate": "/fonts/script/adelia alternate.otf",
  "Bad Coma": "/fonts/Bad Coma.ttf",
  "BAD GRUNGE": "/fonts/BAD GRUNGE.ttf",
  "Dabre Grunge": "/fonts/Dabre Grunge.otf",
  "Grunge Manifesto": "/fonts/Grunge Manifesto.otf",
  "Nancy Spungen": "/fonts/Nancy Spungen.otf",
  "Nancy Spungen Basic": "/fonts/Nancy Spungen Basic.otf",
  "PaybAck": "/fonts/PaybAck.ttf",
  "SF Hollywood Hills": "/fonts/hollywood_hills/SF Hollywood Hills.ttf",
  "SF Hollywood Hills Bold": "/fonts/SF Hollywood Hills Bold.ttf",
  "SF Hollywood Hills Bold Italic": "/fonts/hollywood_hills/SF Hollywood Hills Bold Italic.ttf",
  "SF Hollywood Hills Condensed": "/fonts/hollywood_hills/SF Hollywood Hills Condensed.ttf",
  "SF Hollywood Hills Condensed Italic": "/fonts/hollywood_hills/SF Hollywood Hills Condensed Italic.ttf",
  "SF Hollywood Hills Extended": "/fonts/hollywood_hills/SF Hollywood Hills Extended.ttf",
  "SF Hollywood Hills Extended Italic": "/fonts/hollywood_hills/SF Hollywood Hills Extended Italic.ttf",
  "SF Hollywood Hills Italic": "/fonts/SF Hollywood Hills Italic.ttf",
  
  // --- LEMON MILK (Kept as-is for consistency) ---
  "LEMONMILK-BoldItalic": "/fonts/LEMONMILK-BoldItalic.ttf",
  "LEMONMILK-Bold": "/fonts/LEMONMILK-Bold.ttf",
  "LEMONMILK-Light": "/fonts/LEMONMILK-Light.ttf",
  "LEMONMILK-Medium": "/fonts/LEMONMILK-Medium.ttf",
  "LEMONMILK-Regular": "/fonts/LEMONMILK-Regular.ttf",
  
  // --- COOLVETICA (Renamed) ---
  "Coolvetica Hv Comp": "/fonts/Coolvetica-Hv-Comp.ttf",
  "Coolvetica Rg Cond": "/fonts/Coolvetica-Rg-Cond.ttf",
  "Coolvetica Rg Cram": "/fonts/Coolvetica-Rg-Cram.ttf",
  
  // --- OTHER (Renamed/Stabilized) ---
  "Avigea": "/fonts/Avigea.woff2",
  "Avigea Italic": "/fonts/avigea/Avigea Italic.woff2",
  "Brigends Expanded": "/fonts/Brigends Expanded.otf",
  "Moderniz": "/fonts/Moderniz.otf",
  "Newake": "/fonts/NewakeFont-Demo.otf",
  "Tropical Avenue": "/fonts/Tropical Avenue Personal Use Only.ttf",
  "Minecrafter": "/fonts/Minecrafter.Reg.ttf",
  "Minecrafter Alt": "/fonts/Minecrafter.Alt.ttf",
  "Pixel Digivolve": "/fonts/Pixel Digivolve.otf",
  "Pixel Digivolve Italic": "/fonts/Pixel Digivolve Italic.otf",
  "Techno Hideo": "/fonts/techno_hideo.ttf",
  "Techno Hideo Bold": "/fonts/techno_hideo_bold.ttf",
  "BTSE PS2": "/fonts/btseps2.TTF",
  "TR2N": "/fonts/Tr2n.ttf",
  "DS-Digital": "/fonts/DS-DIGIB.TTF",
  "Digital Cards Demo": "/fonts/Digital Cards Demo.ttf",
  "Mandalore": "/fonts/mandalore/mandalore.ttf",
  "Mandalore 3D": "/fonts/mandalore/mandalore3d.ttf",
  "Mandalore 3D Italic": "/fonts/mandalore/mandalore3dital.ttf",
  "Mandalore Condensed": "/fonts/mandalore/mandalorecond.ttf",
  "Mandalore Condensed Italic": "/fonts/mandalore/mandalorecondital.ttf",
  "Mandalore Expanded": "/fonts/mandalore/mandalorexpand.ttf",
  "Mandalore Expanded Italic": "/fonts/mandalore/mandalorexpandital.ttf",
  "Mandalore Gradient": "/fonts/mandalore/mandaloregrad.ttf",
  "Mandalore Gradient Italic": "/fonts/mandalore/mandaloregradital.ttf",
  "Mandalore Halftone": "/fonts/mandalore/mandalorehalf.ttf",
  "Mandalore Halftone Italic": "/fonts/mandalore/mandalorehalfital.ttf",
  "Mandalore Italic": "/fonts/mandalore/mandaloreital.ttf",
  "Mandalore Laser": "/fonts/mandalore/mandalorelaser.ttf",
  "Mandalore Laser Italic": "/fonts/mandalore/mandalorelaserital.ttf",
  "Mandalore Laser Leftalic": "/fonts/mandalore/mandalorelaserleft.ttf",
  "Mandalore Laser Rough": "/fonts/mandalore/mandalorelaserrough.ttf",
  "Mandalore Laser Rough Italic": "/fonts/mandalore/mandalorelaserroughital.ttf",
  "Mandalore Laser Semi-Italic": "/fonts/mandalore/mandalorelasersemital.ttf",
  "Mandalore Laser Super-Italic": "/fonts/mandalore/mandalorelasersuperital.ttf",
  "Mandalore Laser Title": "/fonts/mandalore/mandalorelasertitle.ttf",
  "Mandalore Laser Title Italic": "/fonts/mandalore/mandalorelasertitleital.ttf",
  "Mandalore Leftalic": "/fonts/mandalore/mandaloreleft.ttf",
  "Mandalore Rough": "/fonts/mandalore/mandalorerough.ttf",
  "Mandalore Rough Italic": "/fonts/mandalore/mandaloreroughital.ttf",
  "Mandalore Semi-Italic": "/fonts/mandalore/mandaloresemital.ttf",
  "Mandalore Super-Italic": "/fonts/mandalore/mandaloresuperital.ttf",
  "Mandalore Title": "/fonts/mandaloretitle.ttf",
  "Mandalore Title Italic": "/fonts/mandalore/mandaloretitleital.ttf",
  "Nexa-Heavy": "/fonts/Nexa-Heavy.ttf",
  "Nexa-ExtraLight": "/fonts/Nexa-ExtraLight.ttf",
  "cubic": "/fonts/cubic.ttf",
  "Azonix": "/fonts/Azonix.ttf",
  "Designer": "/fonts/Designer.ttf",
  "Brich": "/fonts/Brich.ttf",
  "Atlantis Famingo DEMO VERSION": "/fonts/atlantis-famingo-demo-version.ttf",
  "Bebas Neue": "/fonts/BebasNeue-Regular.ttf",
  "BebasNeue-Regular": "/fonts/BebasNeue-Regular.ttf",
  "ChettaVissto": "/fonts/ChettaVissto.ttf",
  "Anton": "/fonts/Anton.ttf",
  "Antone DEMO": "/fonts/antone-demo.ttf",
  "Antonio": "/fonts/Antonio.ttf",
  "Maglisto": "/fonts/Maglisto.ttf",
  "Vartigo": "/fonts/Vartigo.ttf",
  "Lacheyard Script": "/fonts/LacheyardScript_PERSONAL_USE_ONLY.otf",
  "Octin College Rg": "/fonts/Octin College Rg.ttf",
  "OpenScript": "/fonts/OpenScript.ttf",
  "Lovelo Black": "/fonts/Lovelo/Commercial/WEB/Lovelo-Black.woff2",
  "Metropolis 1920": "/fonts/Metropolis1920-Regular.otf"
};
