// nightlife-flyers/localFontMap.ts

export const FONT_FILE_MAP: Record<string, string> = {
  // --- STABLE PATHS (No spaces/special chars) ---
  "DIMITRI_": "/fonts/DIMITRI_.TTF",
  "Aliens Among Us": "/fonts/Aliens-Among-Us.ttf",
  "Game Of Squids": "/fonts/Game-Of-Squids.ttf",
  "Aqilah-JRYXK": "/fonts/Aqilah-JRYXK.ttf",
  "EdgeOfTheGalaxyRegular-OVEa6": "/fonts/EdgeOfTheGalaxyRegular-OVEa6.ttf",
  "raidercrusader": "/fonts/raidercrusader.ttf",
  "Oups": "/fonts/Oups.ttf",
  "Doctor Glitch": "/fonts/Doctor-Glitch.ttf",
  "Dear Script (Demo_Font)": "/fonts/dear-script-demo-font.ttf",
  "edosz": "/fonts/edosz.ttf",
  "Galaxia Personal Used": "/fonts/Galaxia-Personal-Used.ttf",
  "Dune_Rise": "/fonts/dune-rise.ttf",
  "who asks satan": "/fonts/who-asks-satan.ttf",
  "African": "/fonts/African.ttf",
  "Asectica Simple Demo": "/fonts/Asectica Simple Demo.ttf",
  "Paint the town": "/fonts/Paint the town-1.ttf",
  "jelani": "/fonts/jelani.otf",
  "Broken Glass": "/fonts/BrokenGlass.ttf",
  "Monoton": "/fonts/Monoton-Regular.ttf",
  "Magiel Black": "/fonts/Magiel-Black.otf",
  "Good Brush": "/fonts/script/Good Brush.otf",
  "Road Rage": "/fonts/script/Road_Rage.otf",
  "Mitshuka": "/fonts/script/Mitshuka.otf",
  "Bigtimes": "/fonts/script/Bigtimes.otf",
  "Adelia Alternate": "/fonts/script/adelia alternate.otf",
  "Bad Coma": "/fonts/Bad Coma.ttf",
  "BAD GRUNGE": "/fonts/BAD GRUNGE.ttf",
  "Grunge Manifesto": "/fonts/Grunge Manifesto.otf",
  "Nancy Spungen": "/fonts/Nancy Spungen.otf",
  "Nancy Spungen Basic": "/fonts/Nancy Spungen Basic.otf",
  "PaybAck": "/fonts/PaybAck.ttf",
  "SF Hollywood Hills": "/fonts/hollywood_hills/SF Hollywood Hills.ttf",
  "SF Hollywood Hills Bold": "/fonts/SF Hollywood Hills Bold.ttf",
  "SF Hollywood Hills Bold Italic": "/fonts/hollywood_hills/SF Hollywood Hills Bold Italic.ttf",
  "SF Hollywood Hills Condensed": "/fonts/hollywood_hills/SF Hollywood Hills Condensed.ttf",
  "SF Hollywood Hills Condensed Italic": "/fonts/hollywood_hills/SF Hollywood Hills Condensed Italic.ttf",
  "SF Hollywood Hills Extended": "/fonts/hollywood_hills/SF Hollywood Hills Extended.ttf",
  "SF Hollywood Hills Extended Italic": "/fonts/hollywood_hills/SF Hollywood Hills Extended Italic.ttf",
  "SF Hollywood Hills Italic": "/fonts/SF Hollywood Hills Italic.ttf",
  
  // --- LEMON MILK (Kept as-is for consistency) ---
  "LEMONMILK-BoldItalic": "/fonts/LEMONMILK-BoldItalic.ttf",
  "LEMONMILK-Bold": "/fonts/LEMONMILK-Bold.ttf",
  "LEMONMILK-Light": "/fonts/LEMONMILK-Light.ttf",
  "LEMONMILK-Medium": "/fonts/LEMONMILK-Medium.ttf",
  "LEMONMILK-Regular": "/fonts/LEMONMILK-Regular.ttf",
  
  // --- COOLVETICA (Renamed) ---
  "Coolvetica Hv Comp": "/fonts/Coolvetica-Hv-Comp.ttf",
  "Coolvetica Rg Cond": "/fonts/Coolvetica-Rg-Cond.ttf",
  "Coolvetica Rg Cram": "/fonts/Coolvetica-Rg-Cram.ttf",
  
  // --- OTHER (Renamed/Stabilized) ---
  "Avigea": "/fonts/Avigea.woff2",
  "Avigea Italic": "/fonts/avigea/Avigea Italic.woff2",
  "Brigends Expanded": "/fonts/Brigends Expanded.otf",
  "Moderniz": "/fonts/Moderniz.otf",
  "Newake": "/fonts/NewakeFont-Demo.otf",
  "Tropical Avenue": "/fonts/Tropical Avenue Personal Use Only.ttf",
  "Minecrafter": "/fonts/Minecrafter.Reg.ttf",
  "Minecrafter Alt": "/fonts/Minecrafter.Alt.ttf",
  "Pixel Digivolve": "/fonts/Pixel Digivolve.otf",
  "Pixel Digivolve Italic": "/fonts/Pixel Digivolve Italic.otf",
  "Techno Hideo": "/fonts/techno_hideo.ttf",
  "Techno Hideo Bold": "/fonts/techno_hideo_bold.ttf",
  "BTSE PS2": "/fonts/btseps2.TTF",
  "TR2N": "/fonts/Tr2n.ttf",
  "DS-Digital": "/fonts/DS-DIGIB.TTF",
  "Digital Cards Demo": "/fonts/Digital Cards Demo.ttf",
  "Mandalore": "/fonts/mandalore/mandalore.ttf",
  "Mandalore 3D": "/fonts/mandalore/mandalore3d.ttf",
  "Mandalore 3D Italic": "/fonts/mandalore/mandalore3dital.ttf",
  "Mandalore Condensed": "/fonts/mandalore/mandalorecond.ttf",
  "Mandalore Condensed Italic": "/fonts/mandalore/mandalorecondital.ttf",
  "Mandalore Expanded": "/fonts/mandalore/mandalorexpand.ttf",
  "Mandalore Expanded Italic": "/fonts/mandalore/mandalorexpandital.ttf",
  "Mandalore Gradient": "/fonts/mandalore/mandaloregrad.ttf",
  "Mandalore Gradient Italic": "/fonts/mandalore/mandaloregradital.ttf",
  "Mandalore Halftone": "/fonts/mandalore/mandalorehalf.ttf",
  "Mandalore Halftone Italic": "/fonts/mandalore/mandalorehalfital.ttf",
  "Mandalore Italic": "/fonts/mandalore/mandaloreital.ttf",
  "Mandalore Laser": "/fonts/mandalore/mandalorelaser.ttf",
  "Mandalore Laser Italic": "/fonts/mandalore/mandalorelaserital.ttf",
  "Mandalore Laser Leftalic": "/fonts/mandalore/mandalorelaserleft.ttf",
  "Mandalore Laser Rough": "/fonts/mandalore/mandalorelaserrough.ttf",
  "Mandalore Laser Rough Italic": "/fonts/mandalore/mandalorelaserroughital.ttf",
  "Mandalore Laser Semi-Italic": "/fonts/mandalore/mandalorelasersemital.ttf",
  "Mandalore Laser Super-Italic": "/fonts/mandalore/mandalorelasersuperital.ttf",
  "Mandalore Laser Title": "/fonts/mandalore/mandalorelasertitle.ttf",
  "Mandalore Laser Title Italic": "/fonts/mandalore/mandalorelasertitleital.ttf",
  "Mandalore Leftalic": "/fonts/mandalore/mandaloreleft.ttf",
  "Mandalore Rough": "/fonts/mandalore/mandalorerough.ttf",
  "Mandalore Rough Italic": "/fonts/mandalore/mandaloreroughital.ttf",
  "Mandalore Semi-Italic": "/fonts/mandalore/mandaloresemital.ttf",
  "Mandalore Super-Italic": "/fonts/mandalore/mandaloresuperital.ttf",
  "Mandalore Title": "/fonts/mandaloretitle.ttf",
  "Mandalore Title Italic": "/fonts/mandalore/mandaloretitleital.ttf",
  "Nexa-Heavy": "/fonts/Nexa-Heavy.ttf",
  "Nexa-ExtraLight": "/fonts/Nexa-ExtraLight.ttf",
  "cubic": "/fonts/cubic.ttf",
  "Azonix": "/fonts/Azonix.ttf",
  "Designer": "/fonts/Designer.ttf",
  "Brich": "/fonts/Brich.ttf",
  "Atlantis Famingo DEMO VERSION": "/fonts/atlantis-famingo-demo-version.ttf",
  "Bebas Neue": "/fonts/BebasNeue-Regular.ttf",
  "BebasNeue-Regular": "/fonts/BebasNeue-Regular.ttf",
  "ChettaVissto": "/fonts/ChettaVissto.ttf",
  "Anton": "/fonts/Anton.ttf",
  "Antone DEMO": "/fonts/antone-demo.ttf",
  "Antonio": "/fonts/Antonio.ttf",
  "Maglisto": "/fonts/Maglisto.ttf",
  "Vartigo": "/fonts/Vartigo.ttf",
  "Lacheyard Script": "/fonts/LacheyardScript_PERSONAL_USE_ONLY.otf",
  "Octin College Rg": "/fonts/Octin College Rg.ttf",
  "OpenScript": "/fonts/OpenScript.ttf"
};
