export type SceneLayerType = "midground" | "foreground" | "overlay" | "color-grade";
export type SceneLayerRenderMode = "sticker" | "flare";

export type ScenePackLayer = {
  id: string;
  name: string;
  file: string;
  type: SceneLayerType;
  renderAs: SceneLayerRenderMode;
  blendMode?: string;
  opacity?: number;
  x: number;
  y: number;
  scale: number;
  rotation?: number;
  layerOffset?: number;
  locked?: boolean;
  tint?: number;
  tintMode?: "hue" | "colorize";
  isTexture?: boolean;
};

export type ScenePackEmoji = {
  id: string;
  name: string;
  char: string;
  x: number;
  y: number;
  scale: number;
  rotation?: number;
  opacity?: number;
  layerOffset?: number;
  locked?: boolean;
  tint?: number;
};

export type ScenePack = {
  id: string;
  name: string;
  mood: string;
  defaultTextColor: string;
  accentColor: string;
  preview: string;
  background: string;
  manifest: string;
  backgroundScale?: number;
  backgroundPosX?: number;
  backgroundPosY?: number;
  vignetteStrength?: number;
  hue?: number;
  layers: ScenePackLayer[];
  emojis?: ScenePackEmoji[];
};

const sceneAsset = (pack: string, file: string) => `/scene-assets/${pack}/${file}`;
const commonAsset = (file: string) => sceneAsset("common", file);

export const SCENE_PACKS: ReadonlyArray<ScenePack> = [
  {
    id: "industrial-legend",
    name: "Industrial Legend",
    mood: "anchored car-culture composition",
    defaultTextColor: "#FFE600",
    accentColor: "#FF2448",
    preview: "/scene-assets/industrial-legend/preview.png",
    background: "/scene-assets/industrial-legend/warehouse-amber.svg",
    manifest: sceneAsset("industrial-legend", "manifest.json"),
    backgroundScale: 1,
    vignetteStrength: 0.42,
    hue: 0,
    layers: [
      {
        id: "bottom-info-band",
        name: "Bottom Info Band",
        file: sceneAsset("industrial-legend", "bottom-info-band.svg"),
        type: "midground",
        renderAs: "sticker",
        blendMode: "normal",
        opacity: 0.96,
        x: 50,
        y: 90.5,
        scale: 1,
        layerOffset: 1,
      },
      {
        id: "car-ground-shadow",
        name: "Ground Shadow",
        file: sceneAsset("industrial-legend", "car-ground-shadow.svg"),
        type: "midground",
        renderAs: "sticker",
        blendMode: "multiply",
        opacity: 0.86,
        x: 50,
        y: 69.5,
        scale: 0.92,
        layerOffset: -5,
      },
      {
        id: "muscle-car-hero",
        name: "Hero Car",
        file: sceneAsset("industrial-legend", "muscle-car-hero.svg"),
        type: "foreground",
        renderAs: "sticker",
        blendMode: "normal",
        opacity: 1,
        x: 51,
        y: 56.2,
        scale: 0.93,
        rotation: -1,
        layerOffset: 6,
      },
      {
        id: "social-rail",
        name: "Social Rail",
        file: sceneAsset("industrial-legend", "social-rail.svg"),
        type: "foreground",
        renderAs: "sticker",
        blendMode: "normal",
        opacity: 0.96,
        x: 13.5,
        y: 33,
        scale: 0.8,
        layerOffset: 5,
      },
      {
        id: "warm-dust",
        name: "Warm Dust",
        file: sceneAsset("industrial-legend", "warm-dust.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.5,
        x: 50,
        y: 50,
        scale: 1,
        layerOffset: -18,
      },
    ],
  },
  {
    id: "neon-club",
    name: "Neon Club",
    mood: "laser stage energy",
    defaultTextColor: "#FFFFFF",
    accentColor: "#39FF14",
    preview: "/DJ/club01.jpg",
    background: "/DJ/club01.jpg",
    manifest: sceneAsset("neon-club", "manifest.json"),
    backgroundScale: 1.02,
    vignetteStrength: 0.5,
    hue: -4,
    layers: [
      {
        id: "laser-beams",
        name: "Laser Beams",
        file: sceneAsset("neon-club", "laser-beams.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.42,
        x: 50,
        y: 38,
        scale: 1,
        layerOffset: 8,
      },
      {
        id: "blue-streak",
        name: "Blue Streak Flare",
        file: "/flares/flareBlue01.png",
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.36,
        x: 44,
        y: 43,
        scale: 0.64,
        rotation: -14,
        layerOffset: 13,
      },
      {
        id: "club-particles",
        name: "Club Particles",
        file: sceneAsset("neon-club", "particles.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.26,
        x: 50,
        y: 46,
        scale: 0.95,
        layerOffset: 10,
      },
      {
        id: "stage-glow",
        name: "Stage Glow",
        file: sceneAsset("neon-club", "glow-overlay.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.28,
        x: 50,
        y: 48,
        scale: 1,
        layerOffset: 11,
      },
      {
        id: "vignette",
        name: "Edge Depth",
        file: sceneAsset("neon-club", "vignette.svg"),
        type: "color-grade",
        renderAs: "flare",
        blendMode: "multiply",
        opacity: 0.44,
        x: 50,
        y: 50,
        scale: 1.06,
        layerOffset: 0,
      },
    ],
  },
  {
    id: "miami-luxe",
    name: "Miami Luxe",
    mood: "luxury nightlife",
    defaultTextColor: "#F6C76A",
    accentColor: "#00E5FF",
    preview: "/mood-brief/rooftop-party:cinematic.png",
    background: "/mood-brief/rooftop-party:cinematic.png",
    manifest: sceneAsset("miami-luxe", "manifest.json"),
    backgroundScale: 1.04,
    vignetteStrength: 0.66,
    hue: 0,
    layers: [
      {
        id: "skyline",
        name: "Skyline",
        file: sceneAsset("miami-luxe", "skyline.svg"),
        type: "midground",
        renderAs: "sticker",
        opacity: 0.96,
        x: 50,
        y: 71,
        scale: 0.92,
        layerOffset: -10,
      },
      {
        id: "palm-shadow",
        name: "Palm Shadow",
        file: commonAsset("palm-shadow.svg"),
        type: "foreground",
        renderAs: "flare",
        blendMode: "normal",
        opacity: 0.86,
        x: 50,
        y: 54,
        scale: 1,
        layerOffset: 10,
      },
      {
        id: "cocktail-row",
        name: "Cocktail Row",
        file: commonAsset("cocktail-row.svg"),
        type: "foreground",
        renderAs: "sticker",
        blendMode: "screen",
        opacity: 0.88,
        x: 50,
        y: 75,
        scale: 0.42,
        layerOffset: 12,
      },
      {
        id: "smoke-ribbons",
        name: "Ocean Smoke",
        file: commonAsset("smoke-ribbons.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.52,
        x: 50,
        y: 54,
        scale: 1.02,
        layerOffset: 14,
      },
      {
        id: "cyan-glow",
        name: "Cyan Glow",
        file: sceneAsset("miami-luxe", "glow-overlay.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.78,
        x: 50,
        y: 50,
        scale: 1.08,
        layerOffset: 16,
      },
      {
        id: "gold-particles",
        name: "Gold Particles",
        file: sceneAsset("miami-luxe", "particles.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.76,
        x: 50,
        y: 48,
        scale: 1.02,
        layerOffset: 18,
      },
      {
        id: "warm-sun-flare",
        name: "Warm Sun Flare",
        file: "/flares/sun01.png",
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.72,
        x: 76,
        y: 28,
        scale: 0.8,
        layerOffset: 20,
      },
      {
        id: "palms-foreground",
        name: "Palm Foreground",
        file: sceneAsset("miami-luxe", "palms-foreground.svg"),
        type: "foreground",
        renderAs: "flare",
        opacity: 0.9,
        x: 50,
        y: 54,
        scale: 1,
        layerOffset: 22,
      },
      {
        id: "vignette",
        name: "Deep Vignette",
        file: sceneAsset("miami-luxe", "vignette.svg"),
        type: "color-grade",
        renderAs: "flare",
        blendMode: "multiply",
        opacity: 0.74,
        x: 50,
        y: 50,
        scale: 1.06,
        layerOffset: 26,
      },
    ],
    emojis: [
      { id: "cocktail", name: "Cocktail", char: "🍸", x: 18, y: 76, scale: 0.62, rotation: -10, opacity: 0.9, layerOffset: 28 },
      { id: "champagne", name: "Champagne", char: "🍾", x: 84, y: 70, scale: 0.64, rotation: 12, opacity: 0.9, layerOffset: 28 },
      { id: "sparkle", name: "Sparkle", char: "✨", x: 70, y: 18, scale: 0.58, rotation: 0, opacity: 0.88, layerOffset: 28 },
    ],
  },
  {
    id: "bottle-service",
    name: "Bottle Service",
    mood: "vip gold table",
    defaultTextColor: "#F8D47A",
    accentColor: "#FF2FA0",
    preview: "/mood-brief/luxury-vip.club-dark:cinematic.png",
    background: "/mood-brief/luxury-vip.club-dark:cinematic.png",
    manifest: sceneAsset("bottle-service", "manifest.json"),
    backgroundScale: 1.06,
    vignetteStrength: 0.7,
    hue: 0,
    layers: [
      {
        id: "paint-gold",
        name: "Gold Paint Texture",
        file: "/textures/paint02.png",
        type: "overlay",
        renderAs: "flare",
        blendMode: "overlay",
        opacity: 0.78,
        x: 48,
        y: 54,
        scale: 1.12,
        rotation: 9,
        layerOffset: 1,
        tint: 34,
        tintMode: "colorize",
        isTexture: true,
      },
      {
        id: "vip-frame",
        name: "VIP Gold Frame",
        file: sceneAsset("bottle-service", "vip-frame.svg"),
        type: "foreground",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.82,
        x: 50,
        y: 50,
        scale: 1.02,
        layerOffset: 10,
      },
      {
        id: "bottle-cluster",
        name: "Bottle Cluster",
        file: commonAsset("bottle-cluster.svg"),
        type: "foreground",
        renderAs: "sticker",
        blendMode: "screen",
        opacity: 0.92,
        x: 72,
        y: 63,
        scale: 0.5,
        rotation: 4,
        layerOffset: 12,
      },
      {
        id: "spark-fountain",
        name: "Spark Fountain",
        file: sceneAsset("bottle-service", "spark-fountain.svg"),
        type: "midground",
        renderAs: "sticker",
        blendMode: "screen",
        opacity: 0.88,
        x: 78,
        y: 48,
        scale: 0.76,
        layerOffset: 14,
      },
      {
        id: "champagne-glow",
        name: "Champagne Glow",
        file: sceneAsset("bottle-service", "glow-overlay.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.74,
        x: 50,
        y: 50,
        scale: 1.06,
        layerOffset: 16,
      },
      {
        id: "amber-burst",
        name: "Amber Burst",
        file: "/flares/flare03.png",
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.8,
        x: 62,
        y: 33,
        scale: 0.86,
        rotation: -8,
        layerOffset: 18,
      },
      {
        id: "gold-dust",
        name: "Gold Dust",
        file: sceneAsset("bottle-service", "gold-dust.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.7,
        x: 50,
        y: 48,
        scale: 1,
        layerOffset: 20,
      },
      {
        id: "star-confetti",
        name: "Star Confetti",
        file: commonAsset("star-confetti.svg"),
        type: "overlay",
        renderAs: "sticker",
        blendMode: "screen",
        opacity: 0.86,
        x: 50,
        y: 50,
        scale: 0.96,
        layerOffset: 22,
      },
      {
        id: "vignette",
        name: "VIP Vignette",
        file: sceneAsset("bottle-service", "vignette.svg"),
        type: "color-grade",
        renderAs: "flare",
        blendMode: "multiply",
        opacity: 0.74,
        x: 50,
        y: 50,
        scale: 1.06,
        layerOffset: 26,
      },
    ],
    emojis: [
      { id: "bottle", name: "Bottle", char: "🍾", x: 21, y: 63, scale: 0.68, rotation: -14, opacity: 0.92, layerOffset: 28 },
      { id: "cheers", name: "Cheers", char: "🥂", x: 82, y: 78, scale: 0.62, rotation: 9, opacity: 0.9, layerOffset: 28 },
      { id: "sparkle", name: "Sparkle", char: "✨", x: 30, y: 24, scale: 0.56, opacity: 0.9, layerOffset: 28 },
    ],
  },
  {
    id: "afrobeats-night",
    name: "Afrobeats Night",
    mood: "warm rooftop rhythm",
    defaultTextColor: "#FFE08A",
    accentColor: "#19D27C",
    preview: "/mood-brief/rooftop-party:premium.png",
    background: "/mood-brief/rooftop-party:premium.png",
    manifest: sceneAsset("afrobeats-night", "manifest.json"),
    backgroundScale: 1.04,
    vignetteStrength: 0.62,
    hue: 4,
    layers: [
      {
        id: "sunset-haze",
        name: "Sunset Haze",
        file: sceneAsset("afrobeats-night", "sunset-haze.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.72,
        x: 50,
        y: 42,
        scale: 1.04,
        layerOffset: 8,
      },
      {
        id: "pattern-band",
        name: "Rhythm Pattern",
        file: sceneAsset("afrobeats-night", "pattern-band.svg"),
        type: "midground",
        renderAs: "sticker",
        opacity: 0.86,
        x: 50,
        y: 70,
        scale: 0.92,
        layerOffset: -6,
      },
      {
        id: "neon-wave",
        name: "Neon Rhythm Wave",
        file: commonAsset("neon-wave.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.82,
        x: 50,
        y: 50,
        scale: 0.94,
        layerOffset: 10,
      },
      {
        id: "hookah-smoke",
        name: "Hookah Smoke",
        file: "/emojis.com/hookah-with-smoke.png",
        type: "foreground",
        renderAs: "sticker",
        blendMode: "normal",
        opacity: 0.9,
        x: 20,
        y: 67,
        scale: 0.58,
        rotation: -7,
        layerOffset: 12,
      },
      {
        id: "warm-foreground",
        name: "Warm Foreground",
        file: sceneAsset("afrobeats-night", "foreground-palms.svg"),
        type: "foreground",
        renderAs: "flare",
        opacity: 0.88,
        x: 50,
        y: 56,
        scale: 1,
        layerOffset: 14,
      },
      {
        id: "gold-particles",
        name: "Warm Particles",
        file: sceneAsset("afrobeats-night", "gold-particles.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.68,
        x: 50,
        y: 48,
        scale: 1,
        layerOffset: 16,
      },
      {
        id: "paint-warm",
        name: "Warm Paint Texture",
        file: "/textures/paint04.png",
        type: "overlay",
        renderAs: "flare",
        blendMode: "overlay",
        opacity: 0.72,
        x: 52,
        y: 55,
        scale: 1.12,
        rotation: -5,
        layerOffset: 18,
        tint: 78,
        tintMode: "colorize",
        isTexture: true,
      },
      {
        id: "vignette",
        name: "Warm Vignette",
        file: sceneAsset("afrobeats-night", "vignette.svg"),
        type: "color-grade",
        renderAs: "flare",
        blendMode: "multiply",
        opacity: 0.7,
        x: 50,
        y: 50,
        scale: 1.06,
        layerOffset: 26,
      },
    ],
    emojis: [
      { id: "dance", name: "Dance", char: "💃", x: 83, y: 68, scale: 0.68, rotation: 9, opacity: 0.92, layerOffset: 28 },
      { id: "music", name: "Music", char: "🎶", x: 18, y: 34, scale: 0.62, rotation: -10, opacity: 0.9, layerOffset: 28 },
      { id: "fire", name: "Fire", char: "🔥", x: 70, y: 25, scale: 0.56, rotation: 5, opacity: 0.88, layerOffset: 28 },
    ],
  },
  {
    id: "latin-night",
    name: "Latin Night",
    mood: "tropical street heat",
    defaultTextColor: "#FFFFFF",
    accentColor: "#FF3D5A",
    preview: "/artists-bg/tropical01.jpg",
    background: "/artists-bg/tropical01.jpg",
    manifest: sceneAsset("latin-night", "manifest.json"),
    backgroundScale: 1.04,
    vignetteStrength: 0.64,
    hue: 2,
    layers: [
      {
        id: "palm-midground",
        name: "Palm Midground",
        file: sceneAsset("latin-night", "palm-midground.svg"),
        type: "midground",
        renderAs: "sticker",
        opacity: 0.88,
        x: 50,
        y: 58,
        scale: 0.94,
        layerOffset: -5,
      },
      {
        id: "lantern-glow",
        name: "Lantern Glow",
        file: sceneAsset("latin-night", "lantern-glow.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.82,
        x: 50,
        y: 45,
        scale: 1.04,
        layerOffset: 8,
      },
      {
        id: "cocktail-row",
        name: "Cocktail Row",
        file: commonAsset("cocktail-row.svg"),
        type: "foreground",
        renderAs: "sticker",
        blendMode: "screen",
        opacity: 0.84,
        x: 49,
        y: 73,
        scale: 0.42,
        layerOffset: 10,
      },
      {
        id: "confetti",
        name: "Confetti",
        file: sceneAsset("latin-night", "confetti.svg"),
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.68,
        x: 50,
        y: 45,
        scale: 1,
        layerOffset: 12,
      },
      {
        id: "white-flare",
        name: "White Flare",
        file: "/flares/white01.png",
        type: "overlay",
        renderAs: "flare",
        blendMode: "screen",
        opacity: 0.58,
        x: 54,
        y: 34,
        scale: 0.72,
        layerOffset: 14,
      },
      {
        id: "foreground-leaves",
        name: "Foreground Leaves",
        file: sceneAsset("latin-night", "foreground-leaves.svg"),
        type: "foreground",
        renderAs: "flare",
        opacity: 0.92,
        x: 50,
        y: 56,
        scale: 1,
        layerOffset: 18,
      },
      {
        id: "star-confetti",
        name: "Star Confetti",
        file: commonAsset("star-confetti.svg"),
        type: "overlay",
        renderAs: "sticker",
        blendMode: "screen",
        opacity: 0.7,
        x: 50,
        y: 50,
        scale: 0.92,
        layerOffset: 20,
      },
      {
        id: "vignette",
        name: "Tropical Vignette",
        file: sceneAsset("latin-night", "vignette.svg"),
        type: "color-grade",
        renderAs: "flare",
        blendMode: "multiply",
        opacity: 0.72,
        x: 50,
        y: 50,
        scale: 1.06,
        layerOffset: 26,
      },
    ],
    emojis: [
      { id: "tropical-drink", name: "Tropical Drink", char: "🍹", x: 82, y: 73, scale: 0.62, rotation: 10, opacity: 0.92, layerOffset: 28 },
      { id: "party", name: "Party", char: "🎉", x: 19, y: 34, scale: 0.58, rotation: -8, opacity: 0.9, layerOffset: 28 },
      { id: "kiss", name: "Kiss", char: "💋", x: 72, y: 23, scale: 0.5, rotation: 8, opacity: 0.86, layerOffset: 28 },
    ],
  },
];
