import type { CompositionDirectorInput } from "./types.ts";
export const MOJITO_COMPOSITION_FIXTURE:CompositionDirectorInput={
  format:"square",
  scene:{confidence:.91,creativeDecisions:{story:"luxury-tropical-brunch",hero:{type:"subject",confidence:.98},composition:{visualWeight:"right",typeField:"left",typeFieldConfidence:.95,preferredPattern:"left-premium-stack",stackAlignment:"left",stackRect:{x:6,y:13,width:46,height:72},overlapPolicy:"subtle"},hierarchy:{headlinePower:100,accentMaxRatio:.42,bodyMaxRatio:.25,dateMaxRatio:.26,venueMaxRatio:.18,badgeMaxRatio:.22,presenterMaxRatio:.14},densityPolicy:{policy:"low",maxVisibleGroups:5,maxBodyLines:3,mergeSecondaryCopy:true,hideLowPriorityCopy:true}},protectionZones:[{target:"face",rect:{x:58,y:13,width:31,height:35},importance:"critical",allowOverlapRatio:0},{target:"drink",rect:{x:59,y:62,width:15,height:25},importance:"high",allowOverlapRatio:.05}],constraints:[],opportunities:[],reasoning:[],warnings:[]},
  creativeDirection:{id:"mojito-direction",posterIdentity:"lifestyle-editorial",posterDNA:"tropical-lifestyle",visualEnergy:"medium",creativeRisk:"controlled",informationDensity:"low",composition:{family:"left-premium-stack",typeField:"left",alignment:"left",stackRect:{x:6,y:13,width:46,height:72},overlapPolicy:"subtle",oneColumn:true,protectSceneZones:true,reason:"Subject right; type left."},copyArchitecture:[],hierarchy:{headlinePower:100,accentMaxRatio:.42,bodyMaxRatio:.25,dateMaxRatio:.26,venueMaxRatio:.18,badgeMaxRatio:.22,presenterMaxRatio:.14,headlineMustWinBy:2},signatureMove:{move:"script-cross",intensity:"subtle",target:"accent",reason:"Organic brunch accent",parameters:{},fallback:"editorial-spacing"},constraints:[],opportunities:[]},
  text:{headline:"MOJITO MONDAZE",accent:"Brunch Vibes",details:"Tropical rhythms • Afrobeats • Latin",details2:"Cocktails and island energy",date:"Monday",time:"4PM til late",venue:"Sky Lounge Miami",price:"Entry $50",presenter:"Presented by Sky Lounge"},
  subject:{rect:{x:47,y:2,width:53,height:98},visibleRect:{x:48,y:2,width:52,height:98},centroid:{x:73,y:55},faceRect:{x:59,y:14,width:29,height:32},side:"right",crop:"close",saliency:.95,visualMass:.88},
  negativeSpace:[{id:"left",rect:{x:4,y:9,width:47,height:78},score:.9}],busyZones:[{x:55,y:8,width:42,height:80}],darkZones:[{x:4,y:9,width:47,height:78}]
};
