import type { TypographyDirectorInput } from "./types.ts";

export const MOJITO_TYPOGRAPHY_FIXTURE: TypographyDirectorInput = {
  scene: {
    confidence: 0.93,
    creativeDecisions: {
      story: "luxury-tropical-brunch",
      hero: { type: "subject" },
      composition: {
        typeField: "left",
        preferredPattern: "left-premium-stack",
        stackAlignment: "left",
      },
      hierarchy: {
        headlinePower: 100,
        accentMaxRatio: 0.42,
        bodyMaxRatio: 0.25,
        dateMaxRatio: 0.24,
        venueMaxRatio: 0.18,
        badgeMaxRatio: 0.2,
        presenterMaxRatio: 0.13,
      },
      typographyPolicy: "clean-lifestyle",
      densityPolicy: { policy: "low" },
      effectPolicy: { policy: "restrained" },
    },
  },
  creativeDirection: {
    posterIdentity: "lifestyle-editorial",
    posterDNA: "tropical-lifestyle",
    visualEnergy: "medium",
    creativeRisk: "controlled",
    informationDensity: "low",
    hierarchy: {
      headlinePower: 100,
      accentMaxRatio: 0.42,
      bodyMaxRatio: 0.25,
      dateMaxRatio: 0.24,
      venueMaxRatio: 0.18,
      badgeMaxRatio: 0.2,
      presenterMaxRatio: 0.13,
      headlineMustWinBy: 1.9,
    },
    typography: {
      headlinePersonality: "condensed-editorial",
      accentPersonality: "organic-script",
      bodyPersonality: "clean-grotesk",
      headlineTreatment: "clean",
      trackingPolicy: "tight",
      bodyCase: "uppercase",
      bodyTracking: 0.08,
      bodyLineHeight: 0.9,
      maxFontFamilies: 2,
      allowScriptAccent: true,
    },
    signatureMove: {
      move: "script-cross",
      intensity: "medium",
      target: "accent",
      parameters: { accentScale: 0.88, rotation: -5, overlapRatio: 0.04 },
      fallback: "editorial-spacing",
    },
    effects: {
      policy: "restrained",
      maxGlow: 0.1,
      maxShadow: 0.32,
      maxTexture: 0.08,
    },
  },
  composition: {
    family: "left-premium-stack",
    alignment: "left",
    typeField: "left",
    overlapPolicy: "subtle",
  },
  copyArchitecture: {
    id: "copy-mojito",
    tone: "premium-lifestyle",
    density: "low",
    groups: [
      { id: "identity", role: "identity", treatment: "hero", text: "MOJITO\nMONDAZE", case: "uppercase", priority: 1, maxLines: 2, powerRatio: 1 },
      { id: "emotion", role: "emotion", treatment: "accent", text: "Brunch Vibes", case: "titlecase", priority: 2, maxLines: 1, powerRatio: 0.42 },
      { id: "experience", role: "experience", treatment: "metadata", text: "TROPICAL RHYTHMS • AFROBEATS • LATIN\nCOCKTAILS & ISLAND ENERGY", case: "uppercase", priority: 3, maxLines: 2, powerRatio: 0.25 },
      { id: "logistics", role: "logistics", treatment: "metadata", text: "MONDAY • 4PM TIL LATE", case: "uppercase", priority: 3, maxLines: 1, powerRatio: 0.24 },
      { id: "venue", role: "venue", treatment: "footer", text: "SKY LOUNGE MIAMI", case: "uppercase", priority: 4, maxLines: 1, powerRatio: 0.18 },
      { id: "badge", role: "badge", treatment: "badge", text: "ENTRY\n$50", case: "uppercase", priority: 4, maxLines: 2, powerRatio: 0.2 },
    ],
  },
  availableFonts: {
    fonts: [
      "Anton",
      "Bebas Neue",
      "Oswald",
      "Playfair Display",
      "LEMONMILK-Regular",
      "Manrope",
      "Dancing Script",
      "Great Vibes",
      "Pacifico",
      "Space Grotesk",
    ],
    fallbackFamilies: {
      headline: ["Arial Narrow", "Impact", "sans-serif"],
      accent: ["cursive", "sans-serif"],
      metadata: ["LEMONMILK-Regular", "Bebas Neue", "sans-serif"],
    },
  },
  userPreferences: {
    preferredHeadlineFonts: ["Bebas Neue", "Anton"],
    preferredAccentFonts: ["Great Vibes", "Dancing Script"],
    preferredBodyFonts: ["LEMONMILK-Regular", "Manrope"],
    forbiddenFonts: [],
    maxFontFamilies: 2,
    allowScriptAccent: true,
    preserveCurrentFonts: false,
  },
};

export const TECHNO_TYPOGRAPHY_FIXTURE: TypographyDirectorInput = {
  scene: {
    confidence: 0.87,
    creativeDecisions: {
      story: "techno-underground",
      hero: { type: "headline" },
      composition: {
        typeField: "top",
        preferredPattern: "diagonal-energy",
        stackAlignment: "center",
      },
      typographyPolicy: "industrial-minimal",
      densityPolicy: { policy: "low" },
      effectPolicy: { policy: "cinematic" },
    },
  },
  creativeDirection: {
    posterIdentity: "underground-industrial",
    posterDNA: "underground-rave",
    visualEnergy: "high",
    creativeRisk: "bold",
    informationDensity: "low",
    typography: {
      headlinePersonality: "industrial-minimal",
      accentPersonality: "industrial-minimal",
      bodyPersonality: "clean-grotesk",
      maxFontFamilies: 2,
      allowScriptAccent: false,
    },
    signatureMove: {
      move: "single-electric-glow",
      intensity: "medium",
      target: "headline",
      parameters: { glowBoost: 0.16 },
    },
    effects: {
      policy: "cinematic",
      maxGlow: 0.3,
      maxShadow: 0.5,
      maxTexture: 0.24,
    },
  },
  composition: {
    family: "diagonal-energy",
    alignment: "center",
    typeField: "top",
    overlapPolicy: "controlled",
  },
  copyArchitecture: {
    groups: [
      { id: "identity", role: "identity", treatment: "hero", text: "NEURAL CORE", maxLines: 2 },
      { id: "emotion", role: "emotion", treatment: "accent", text: "WAREHOUSE TECHNO", maxLines: 1 },
      { id: "music", role: "music", treatment: "metadata", text: "INDUSTRIAL FREQUENCIES • DEEP TECHNO", maxLines: 2 },
      { id: "logistics", role: "logistics", treatment: "metadata", text: "SATURDAY • 11PM", maxLines: 1 },
      { id: "venue", role: "venue", treatment: "footer", text: "SECTOR 9", maxLines: 1 },
    ],
  },
  availableFonts: {
    fonts: ["Orbitron", "Rajdhani", "Space Grotesk", "IBM Plex Mono", "LEMONMILK-Regular", "Oswald"],
  },
};
