import type {CreativeConstraint,CreativeDirection,CreativeDirectorInput} from './types.ts';
export function buildConstraints(input:CreativeDirectorInput,p:Pick<CreativeDirection,'posterIdentity'|'informationDensity'|'composition'|'hierarchy'|'effects'|'signatureMove'>):CreativeConstraint[]{const out:CreativeConstraint[]=[
{id:'one-anchor',severity:'hard',weight:100,description:'One unmistakable visual anchor.'},
{id:'headline-wins',severity:'hard',weight:100,description:'Headline remains first textual read.',parameters:{headlineMustWinBy:p.hierarchy.headlineMustWinBy}},
{id:'accent-subordinate',severity:'hard',weight:98,description:'Accent cannot become a second headline.',parameters:{maxRatio:p.hierarchy.accentMaxRatio}},
{id:'body-is-metadata',severity:'hard',weight:96,description:'Support copy is metadata, not paragraph.',parameters:{maxRatio:p.hierarchy.bodyMaxRatio}},
{id:'one-signature-move',severity:'strong',weight:90,description:'Use one memorable move.',parameters:{move:p.signatureMove.move}},
{id:'protect-scene',severity:'hard',weight:100,description:'Respect scene protection zones.'},
{id:'renderer-obedience',severity:'hard',weight:100,description:'Renderer may not reinterpret creative direction.'},
{id:'preview-export-parity',severity:'hard',weight:100,description:'Preview and export must match.'}
];if(p.composition.oneColumn)out.push({id:'single-type-system',severity:'hard',weight:94,description:'Render one typography system.'});if(['minimal','low'].includes(p.informationDensity))out.push({id:'low-density',severity:'hard',weight:90,description:'Merge or hide low-priority copy.'});if(p.effects.policy==='restrained')out.push({id:'restrained-effects',severity:'hard',weight:92,description:'Effects stay below configured limits.',parameters:{maxGlow:p.effects.maxGlow,maxTexture:p.effects.maxTexture,maxParticles:p.effects.maxParticles}});if(input.scene.creativeDecisions.hero.type==='subject')out.push({id:'subject-remains-hero',severity:'hard',weight:100,description:'Typography cannot overpower subject.'},{id:'face-gaze-protection',severity:'hard',weight:100,description:'Do not cover face, eyes, smile, or gaze.'});for(const c of input.scene.constraints??[])out.push({id:`scene:${c.id}`,severity:c.hard?'hard':'strong',weight:c.weight,description:c.reason,parameters:c.parameters});return Array.from(new Map(out.map(x=>[x.id,x])).values())}
